// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARgpsD8HuN2Bgs_HG9H_MSYA9ki8YM3kc',
    appId: '1:1013057635854:web:a5ecb2beae4dd86ac35e5f',
    messagingSenderId: '1013057635854',
    projectId: 'book-app-1356e',
    authDomain: 'book-app-1356e.firebaseapp.com',
    databaseURL: 'https://book-app-1356e-default-rtdb.firebaseio.com',
    storageBucket: 'book-app-1356e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuGMkostRI9Jo8pa-KCVDsBuhjgMy1iNs',
    appId: '1:1013057635854:android:8db24c6355a22fe1c35e5f',
    messagingSenderId: '1013057635854',
    projectId: 'book-app-1356e',
    databaseURL: 'https://book-app-1356e-default-rtdb.firebaseio.com',
    storageBucket: 'book-app-1356e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZyzYNaETVHiFddV_S2Wr0p8URi9SD9Hk',
    appId: '1:1013057635854:ios:ba434df9080d6d28c35e5f',
    messagingSenderId: '1013057635854',
    projectId: 'book-app-1356e',
    databaseURL: 'https://book-app-1356e-default-rtdb.firebaseio.com',
    storageBucket: 'book-app-1356e.appspot.com',
    iosClientId:
        '1013057635854-1ade6267ggfidb8ajn6tlnq7pfr20dbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookvApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZyzYNaETVHiFddV_S2Wr0p8URi9SD9Hk',
    appId: '1:1013057635854:ios:ba434df9080d6d28c35e5f',
    messagingSenderId: '1013057635854',
    projectId: 'book-app-1356e',
    databaseURL: 'https://book-app-1356e-default-rtdb.firebaseio.com',
    storageBucket: 'book-app-1356e.appspot.com',
    iosClientId:
        '1013057635854-1ade6267ggfidb8ajn6tlnq7pfr20dbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookvApp',
  );
}
